[2025-03-09T18:26:40.589+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T18:26:40.600+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: a1.insert_data_to_mongodb manual__2025-03-09T18:13:58.550767+00:00 [queued]>
[2025-03-09T18:26:40.603+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: a1.insert_data_to_mongodb manual__2025-03-09T18:13:58.550767+00:00 [queued]>
[2025-03-09T18:26:40.603+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 7
[2025-03-09T18:26:40.609+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): insert_data_to_mongodb> on 2025-03-09 18:13:58.550767+00:00
[2025-03-09T18:26:40.625+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=169) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T18:26:40.627+0000] {standard_task_runner.py:72} INFO - Started process 170 to run task
[2025-03-09T18:26:40.627+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'a1', 'insert_data_to_mongodb', 'manual__2025-03-09T18:13:58.550767+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpe7w2fghc']
[2025-03-09T18:26:40.629+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask insert_data_to_mongodb
[2025-03-09T18:26:40.673+0000] {task_command.py:467} INFO - Running <TaskInstance: a1.insert_data_to_mongodb manual__2025-03-09T18:13:58.550767+00:00 [running]> on host a4ea25182d86
[2025-03-09T18:26:41.114+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='a1' AIRFLOW_CTX_TASK_ID='insert_data_to_mongodb' AIRFLOW_CTX_EXECUTION_DATE='2025-03-09T18:13:58.550767+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-09T18:13:58.550767+00:00'
[2025-03-09T18:26:41.116+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T18:26:41.116+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T18:26:41.117+0000] {logging_mixin.py:190} INFO - Current task name:insert_data_to_mongodb state:running start_date:2025-03-09 18:26:40.600807+00:00
[2025-03-09T18:26:41.117+0000] {logging_mixin.py:190} INFO - Dag name:a1 and current dag run status:running
[2025-03-09T18:26:41.117+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T18:26:41.118+0000] {logging_mixin.py:190} INFO - attampting to insert data to MongoDB....
[2025-03-09T18:26:41.126+0000] {base.py:84} INFO - Retrieving connection 'mongo_default'
[2025-03-09T18:26:41.128+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline.py", line 36, in insert_data_to_mongodb
    client = mongo_hook.get_conn()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mongo/hooks/mongo.py", line 193, in get_conn
    self.client = MongoClient(self.uri, **options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 784, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 529, in parse_uri
    options.update(split_options(opts, validate, warn, normalize))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 360, in split_options
    raise InvalidURI("MongoDB URI options are key=value pairs.") from None
pymongo.errors.InvalidURI: MongoDB URI options are key=value pairs.
[2025-03-09T18:26:41.139+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T18:26:41.139+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 18:26:40.600807+00:00 end:2025-03-09 18:26:41.139152+00:00 duration:0.538345
[2025-03-09T18:26:41.140+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): insert_data_to_mongodb> dag:<DAG: a1> dagrun:<DagRun a1 @ 2025-03-09 18:13:58.550767+00:00: manual__2025-03-09T18:13:58.550767+00:00, state:running, queued_at: 2025-03-09 18:13:58.716090+00:00. externally triggered: True>
[2025-03-09T18:26:41.140+0000] {logging_mixin.py:190} INFO - Failure caused by MongoDB URI options are key=value pairs.
[2025-03-09T18:26:41.140+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=a1, task_id=insert_data_to_mongodb, run_id=manual__2025-03-09T18:13:58.550767+00:00, execution_date=20250309T181358, start_date=20250309T182640, end_date=20250309T182641
[2025-03-09T18:26:41.163+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T18:26:41.164+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 20 for task insert_data_to_mongodb (MongoDB URI options are key=value pairs.; 170)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline.py", line 36, in insert_data_to_mongodb
    client = mongo_hook.get_conn()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mongo/hooks/mongo.py", line 193, in get_conn
    self.client = MongoClient(self.uri, **options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/synchronous/mongo_client.py", line 784, in __init__
    res = uri_parser.parse_uri(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 529, in parse_uri
    options.update(split_options(opts, validate, warn, normalize))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pymongo/uri_parser.py", line 360, in split_options
    raise InvalidURI("MongoDB URI options are key=value pairs.") from None
pymongo.errors.InvalidURI: MongoDB URI options are key=value pairs.
[2025-03-09T18:26:41.204+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T18:26:41.234+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T18:26:41.237+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
