[2025-03-09T18:14:18.398+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-09T18:14:18.421+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: a1.insert_data_to_mongodb scheduled__2025-03-08T00:00:00+00:00 [queued]>
[2025-03-09T18:14:18.432+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: a1.insert_data_to_mongodb scheduled__2025-03-08T00:00:00+00:00 [queued]>
[2025-03-09T18:14:18.433+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-03-09T18:14:18.458+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): insert_data_to_mongodb> on 2025-03-08 00:00:00+00:00
[2025-03-09T18:14:18.509+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=181) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-09T18:14:18.519+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'a1', 'insert_data_to_mongodb', 'scheduled__2025-03-08T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpzu6muh3h']
[2025-03-09T18:14:18.537+0000] {standard_task_runner.py:72} INFO - Started process 190 to run task
[2025-03-09T18:14:18.537+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask insert_data_to_mongodb
[2025-03-09T18:14:18.633+0000] {task_command.py:467} INFO - Running <TaskInstance: a1.insert_data_to_mongodb scheduled__2025-03-08T00:00:00+00:00 [running]> on host de9886b10730
[2025-03-09T18:14:18.870+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='a1' AIRFLOW_CTX_TASK_ID='insert_data_to_mongodb' AIRFLOW_CTX_EXECUTION_DATE='2025-03-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-08T00:00:00+00:00'
[2025-03-09T18:14:18.880+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-09T18:14:18.881+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-09T18:14:18.881+0000] {logging_mixin.py:190} INFO - Current task name:insert_data_to_mongodb state:running start_date:2025-03-09 18:14:18.422141+00:00
[2025-03-09T18:14:18.882+0000] {logging_mixin.py:190} INFO - Dag name:a1 and current dag run status:running
[2025-03-09T18:14:18.882+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-09T18:14:18.884+0000] {logging_mixin.py:190} INFO - attampting to insert data to MongoDB....
[2025-03-09T18:14:18.943+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline.py", line 35, in insert_data_to_mongodb
    mongo_hook = MongoHook(conn_id="mongodb")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mongo/hooks/mongo.py", line 122, in __init__
    conn = self.get_connection(self.mongo_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mongo_default` isn't defined
[2025-03-09T18:14:18.963+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-09T18:14:18.963+0000] {logging_mixin.py:190} INFO - Task start:2025-03-09 18:14:18.422141+00:00 end:2025-03-09 18:14:18.962797+00:00 duration:0.540656
[2025-03-09T18:14:18.964+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): insert_data_to_mongodb> dag:<DAG: a1> dagrun:<DagRun a1 @ 2025-03-08 00:00:00+00:00: scheduled__2025-03-08T00:00:00+00:00, state:running, queued_at: 2025-03-09 18:13:59.811847+00:00. externally triggered: False>
[2025-03-09T18:14:18.964+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `mongo_default` isn't defined
[2025-03-09T18:14:18.964+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=a1, task_id=insert_data_to_mongodb, run_id=scheduled__2025-03-08T00:00:00+00:00, execution_date=20250308T000000, start_date=20250309T181418, end_date=20250309T181418
[2025-03-09T18:14:19.038+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-09T18:14:19.038+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task insert_data_to_mongodb (The conn_id `mongo_default` isn't defined; 190)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/pipeline.py", line 35, in insert_data_to_mongodb
    mongo_hook = MongoHook(conn_id="mongodb")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mongo/hooks/mongo.py", line 122, in __init__
    conn = self.get_connection(self.mongo_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mongo_default` isn't defined
[2025-03-09T18:14:19.094+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-09T18:14:19.169+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-09T18:14:19.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
