[2025-04-24T17:09:03.538+0000] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:09:03.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:09:03.545+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:09:03.544+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:09:11.197+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:09:11.197+0000] {process_utils.py:266} INFO - Waiting up to 5 seconds for processes to exit...
[2025-04-24T17:09:11.204+0000] {logging_mixin.py:190} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7fe7c99a9260>
[2025-04-24T17:09:11.212+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2025-04-24T17:09:11.214+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/weakref.py", line 369, in remove
[2025-04-24T17:09:11.216+0000] {logging_mixin.py:190} WARNING -     def remove(k, selfref=ref(self)):
[2025-04-24T17:09:11.217+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 466, in _exit_gracefully
[2025-04-24T17:09:11.219+0000] {logging_mixin.py:190} WARNING -     self.log.debug("Current Stacktrace is: %s", "\n".join(map(str, inspect.stack())))
[2025-04-24T17:09:11.220+0000] {logging_mixin.py:190} WARNING -                                                                    ^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.221+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1781, in stack
[2025-04-24T17:09:11.224+0000] {logging_mixin.py:190} WARNING -     return getouterframes(sys._getframe(1), context)
[2025-04-24T17:09:11.225+0000] {logging_mixin.py:190} WARNING -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.227+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1756, in getouterframes
[2025-04-24T17:09:11.235+0000] {logging_mixin.py:190} WARNING -     traceback_info = getframeinfo(frame, context)
[2025-04-24T17:09:11.237+0000] {logging_mixin.py:190} WARNING -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.238+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1718, in getframeinfo
[2025-04-24T17:09:11.242+0000] {logging_mixin.py:190} WARNING -     lines, lnum = findsource(frame)
[2025-04-24T17:09:11.243+0000] {logging_mixin.py:190} WARNING -                   ^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.245+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1090, in findsource
[2025-04-24T17:09:11.248+0000] {logging_mixin.py:190} WARNING -     module = getmodule(object, file)
[2025-04-24T17:09:11.255+0000] {logging_mixin.py:190} WARNING -              ^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.256+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1016, in getmodule
[2025-04-24T17:09:11.259+0000] {logging_mixin.py:190} WARNING -     os.path.realpath(f)] = module.__name__
[2025-04-24T17:09:11.261+0000] {logging_mixin.py:190} WARNING -     ^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.263+0000] {logging_mixin.py:190} WARNING -   File "<frozen posixpath>", line 427, in realpath
[2025-04-24T17:09:11.264+0000] {logging_mixin.py:190} WARNING -   File "<frozen posixpath>", line 462, in _joinrealpath
[2025-04-24T17:09:11.266+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 466, in _exit_gracefully
[2025-04-24T17:09:11.268+0000] {logging_mixin.py:190} WARNING -     self.log.debug("Current Stacktrace is: %s", "\n".join(map(str, inspect.stack())))
[2025-04-24T17:09:11.270+0000] {logging_mixin.py:190} WARNING -                                                                    ^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.271+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1781, in stack
[2025-04-24T17:09:11.274+0000] {logging_mixin.py:190} WARNING -     return getouterframes(sys._getframe(1), context)
[2025-04-24T17:09:11.278+0000] {logging_mixin.py:190} WARNING -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.282+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1756, in getouterframes
[2025-04-24T17:09:11.284+0000] {logging_mixin.py:190} WARNING -     traceback_info = getframeinfo(frame, context)
[2025-04-24T17:09:11.287+0000] {logging_mixin.py:190} WARNING -                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.290+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1714, in getframeinfo
[2025-04-24T17:09:11.296+0000] {logging_mixin.py:190} WARNING -     filename = getsourcefile(frame) or getfile(frame)
[2025-04-24T17:09:11.297+0000] {logging_mixin.py:190} WARNING -                ^^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.301+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 970, in getsourcefile
[2025-04-24T17:09:11.306+0000] {logging_mixin.py:190} WARNING -     module = getmodule(object, filename)
[2025-04-24T17:09:11.310+0000] {logging_mixin.py:190} WARNING -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.313+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/inspect.py", line 1016, in getmodule
[2025-04-24T17:09:11.316+0000] {logging_mixin.py:190} WARNING -     os.path.realpath(f)] = module.__name__
[2025-04-24T17:09:11.317+0000] {logging_mixin.py:190} WARNING -     ^^^^^^^^^^^^^^^^^^^
[2025-04-24T17:09:11.319+0000] {logging_mixin.py:190} WARNING -   File "<frozen posixpath>", line 427, in realpath
[2025-04-24T17:09:11.321+0000] {logging_mixin.py:190} WARNING -   File "<frozen posixpath>", line 462, in _joinrealpath
[2025-04-24T17:09:11.328+0000] {logging_mixin.py:190} WARNING -   File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/manager.py", line 470, in _exit_gracefully
[2025-04-24T17:09:11.331+0000] {logging_mixin.py:190} WARNING -     sys.exit(os.EX_OK)
[2025-04-24T17:09:11.332+0000] {logging_mixin.py:190} WARNING - SystemExit: 0
[2025-04-24T17:09:15.577+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:09:15.577+0000] {process_utils.py:266} INFO - Waiting up to 5 seconds for processes to exit...
[2025-04-24T17:11:21.580+0000] {processor.py:186} INFO - Started process (PID=84) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:11:21.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:11:21.588+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:11:21.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:11:43.106+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:11:43.105+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-04-24T17:11:44.287+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:11:44.273+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:11:44.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:11:44.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 22.775 seconds
[2025-04-24T17:12:14.825+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:12:14.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:12:14.832+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:12:14.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:12:30.454+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:12:30.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:12:30.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:12:30.476+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 15.666 seconds
[2025-04-24T17:13:00.979+0000] {processor.py:186} INFO - Started process (PID=162) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:13:00.982+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:13:00.993+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:13:00.992+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:13:15.103+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:13:15.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:13:15.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:13:15.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 14.181 seconds
[2025-04-24T17:13:45.536+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:13:45.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:13:45.542+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:13:45.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:13:59.734+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:13:59.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:13:59.738+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:13:59.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 14.233 seconds
[2025-04-24T17:14:30.774+0000] {processor.py:186} INFO - Started process (PID=228) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:14:30.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:14:30.781+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:14:30.780+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:14:44.398+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:14:44.392+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:14:44.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:14:44.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 13.673 seconds
[2025-04-24T17:15:15.036+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:15:15.038+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:15:15.043+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:15:15.042+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:15:29.761+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:15:29.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:15:29.766+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:15:29.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 14.773 seconds
[2025-04-24T17:16:00.579+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:16:00.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:16:00.587+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:16:00.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:16:14.924+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:16:14.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:16:14.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:16:14.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 14.380 seconds
[2025-04-24T17:16:45.512+0000] {processor.py:186} INFO - Started process (PID=324) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:16:45.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:16:45.519+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:16:45.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:16:59.224+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:16:59.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:16:59.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:16:59.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 13.770 seconds
[2025-04-24T17:17:29.590+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:17:29.592+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:17:29.597+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:17:29.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:17:43.243+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:17:43.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:17:43.246+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:17:43.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 13.685 seconds
[2025-04-24T17:18:14.083+0000] {processor.py:186} INFO - Started process (PID=391) to work on /opt/airflow/dags/gold_dag.py
[2025-04-24T17:18:14.085+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/gold_dag.py for tasks to queue
[2025-04-24T17:18:14.089+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:18:14.088+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:18:25.760+0000] {logging_mixin.py:190} INFO - [2025-04-24T17:18:25.755+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/gold_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/gold_dag.py", line 19, in <module>
    DAG_CONFIG = Variable.get("gold_prediction_dag_config", deserialize_json=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 145, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable gold_prediction_dag_config does not exist'
[2025-04-24T17:18:25.763+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/gold_dag.py
[2025-04-24T17:18:25.782+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/gold_dag.py took 11.710 seconds
